import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/utils/AuthProvider";
// import { Toaster } from "@/components/ui/sonner";
import AdminProvider from "@/utils/AdminProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DesignoBit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <AdminProvider>{children}</AdminProvider>
        </AuthProvider>
        {/* <Toaster /> */}
      </body>
    </html>
  );
}
